urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.simple import direct_to_template

from djangoappengine.utils import on_production_server, have_appserver
from registration.forms import RegistrationFormUniqueEmail
from registration.backends.default.views import RegistrationView


handler500 = 'djangotoolbox.errorviews.server_error'

urlpatterns = patterns('',
    url(r'^$', direct_to_template, {'template': 'main.html'}, name='main'),
    url(r'^word_sets/$', 'lingo.views.word_sets_list', name='word_sets_list'),
    url(r'^word_sets/(?P<pk>\d+)/$', 'lingo.views.word_sets_detail', name='word_sets_detail'),
    url(r'^word_sets/edit/$', 'lingo.views.word_sets_edit', name='word_sets_edit'),
    url(r'^word_sets/(?P<pk>\d+)/edit/$', 'lingo.views.word_sets_edit', name='word_sets_edit'),
    url(r'^accounts/login/$', 'lingo.views.login_user'),
    url(r'^accounts/register/$', RegistrationView.as_view(form_class=RegistrationFormUniqueEmail),
        name='registration_register'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout',
                          {'next_page': '/'}),
    url(r'^accounts/', include('registration.backends.default.urls')),
)

if on_production_server:
    urlpatterns += staticfiles_urlpatterns()

lingo/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.db import models, DatabaseError


class Word(models.Model):
    """
    A word.
    """
    word = models.CharField(max_length=200)
    definition = models.CharField(max_length=500)
    difficulty = models.IntegerField()
    pos = models.CharField(max_length=64)
    word_set = models.ForeignKey('WordSet')

    def __unicode__(self):
        return unicode(self.word)


class WordSet(models.Model):
    """
    A set of words.
    """
    class Meta:
        ordering = ['-pub_date']

    title = models.CharField(max_length=500)
    pub_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)

    def __unicode__(self):
        return unicode(self.title)

    @property
    def words_number(self):
        """
        Return a number of words in the set of words.
        """
        return self.word_set.count()

    def merge(self, word_sets):
        """Merge other WordSets with self.

        Only one copy of the same words having identical definitions is saved.
        Multiple definitions of the same words (i.e. having the same word and
        part of speech - pos - attributes) are merged.
        """
        for word_set in word_sets:
            for word in word_set.word_set.all():
                try:
                    similar_word = self.word_set.get(pos=word.pos, word=word.word)
                except ObjectDoesNotExist:
                    word.word_set = self
                    word.save()
                else:
                    try:
                        similar_word.definition += "; " + word.definition
                        similar_word.save()
                    except DatabaseError:
                        # definitions are too long to fit in one CharField;
                        # the word is deleted and definition lost (not probable)
                        pass
                    word.delete()
            word_set.delete()
        self.save()

lingo/forms.py
#coding=utf-8
from django import forms

from .models import WordSet, Word
from .algorithms import naive, parse_text


class WordSetForm(forms.Form):
    """
    Form used to create a new WordSet or modify an exisiting one.
    """
    title = forms.CharField(max_length=1024, required=False)
    file = forms.FileField(required=False)
    text = forms.CharField(widget=forms.Textarea, required=False)

    def __init__(self, *args, **kwargs):
        self.instance = kwargs.pop('instance', None)
        self.user = kwargs.pop('user')
        super(WordSetForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(WordSetForm, self).clean()
        if not cleaned_data.get('file') and not cleaned_data.get('text'):
            raise forms.ValidationError('Musisz wybrać plik albo wkleić tekst.')
        if not self.instance and not cleaned_data.get('title'):
            raise forms.ValidationError('Musisz wpisać nazwę zestawu.')
        return cleaned_data

    def save(self):
        if not self.instance:
            self.instance = WordSet(title=self.cleaned_data.get('title'), user=self.user)
        file = self.cleaned_data.get('file')
        text = self.cleaned_data.get('text')
        data = file.read() if file else text
        words = parse_text(data)
        #words = naive(words)
        self.instance.save()
        word_difficulty = 0
        for (word, pos) in words:
            Word.objects.create(word=word, pos=pos, definition='',
                                difficulty=word_difficulty, word_set=self.instance)


class WordSetsListForm(forms.Form):
    """
    Form used to modify a list of WordSets.
    """
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(WordSetsListForm, self).__init__(*args, **kwargs)
        self.fields['word_set'] = forms.ModelMultipleChoiceField(
            queryset=self.user.wordset_set.all(),
            widget=forms.widgets.CheckboxSelectMultiple)
        self.submit_action = self.data.get('submit_action', None)

    def save(self):
        word_sets = self.cleaned_data.get('word_set')
        if self.submit_action == 'delete':
            word_sets.delete()
        elif self.submit_action == 'merge':
            target = word_sets[0]
            target.merge(word_sets[1:])


class WordSetsDetailForm(forms.Form):
    """
    Form used to manage specific WordSet.
    """
    def __init__(self, *args, **kwargs):
        self.instance = kwargs.pop('instance', None)
        self.user = kwargs.pop('user', None)
        super(WordSetsDetailForm, self).__init__(*args, **kwargs)
        self.fields['word'] = forms.ModelMultipleChoiceField(
            queryset=self.instance.word_set.all(),
            widget=forms.widgets.CheckboxSelectMultiple)
        self.submit_action = self.data.get('submit_action', None)

    def save(self):
        words = self.cleaned_data.get('word')
        if self.submit_action == 'delete':
            words.delete()

lingo/views.py
#coding=utf-8
from django.core.mail import EmailMessage
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from .forms import WordSetForm, WordSetsListForm, WordSetsDetailForm
from .helpers import generate_txt_file, get_dictionary_data
from .models import Word, WordSet
from conf import EMAIL_HOST_USER


def login_user(request, *args, **kwargs):
    """
    Login the user.
    """
    if request.POST.get('remember_me'):
        request.session.set_expiry(604800)
    return auth_views.login(request, *args, **kwargs)


@login_required
def word_sets_list(request):
    """
    Return the list of WordSets belonging to the user or modify some of them.
    """
    form = WordSetsListForm(request.POST or None, user=request.user)
    if form.is_valid():
        if form.submit_action in ('merge', 'delete'):
            form.save()
        elif form.submit_action == 'download_txt':
            file_content = generate_txt_file(form.cleaned_data.get('word_set', None))
            response = HttpResponse(file_content, content_type='text/plain; charset=utf-8')
            response['Content-Disposition'] = 'attachment; filename="words.txt"'
            return response
        elif form.submit_action == 'download_email':
            file_content = generate_txt_file(form.cleaned_data.get('word_set', None))
            email = EmailMessage('Zestawy słówek', 'Plik znajduje się w załączniku',
                                 EMAIL_HOST_USER, [request.user.email],
                                 attachments=[('words.txt', file_content,
                                               'text/plain; charset=utf-8')])
            email.send()
    if request.method == 'POST':
        return redirect(word_sets_list)
    return render(request, 'word_sets_list.html', {'form': form})


@login_required
def word_sets_detail(request, pk):
    """
    Return details of requested WordSet or modify its contents.
    """
    word_set = get_object_or_404(WordSet, pk=pk, user=request.user)

    if request.method == 'POST' and request.is_ajax():
        if request.POST.get('get_dict_data'):
            word = request.POST.get('word')
            dict_data = get_dictionary_data(word)
            return HttpResponse(dict_data)
        word_set.title = request.POST.get('value')
        word_set.save()
        return HttpResponse()

    form = WordSetsDetailForm(request.POST or None, instance=word_set, user=request.user)
    if form.is_valid():
        if form.submit_action == 'delete':
            form.save()
    if form.submit_action == 'download_txt':
        file_content = generate_txt_file([word_set])
        response = HttpResponse(file_content, content_type='text/plain; charset=utf-8')
        response['Content-Disposition'] = 'attachment; filename="words.txt"'
        return response
    elif form.submit_action == 'download_email':
        file_content = generate_txt_file([word_set])
        email = EmailMessage('Zestawy słówek', 'Plik znajduje się w załączniku',
                             EMAIL_HOST_USER, [request.user.email],
                             attachments=[('words.txt', file_content,
                                           'text/plain; charset=utf-8')])
        email.send()

    if request.method == 'POST':
        return redirect(word_sets_detail, pk=pk)
    return render(request, 'word_sets_detail.html',
                  {'word_set_pk': pk, 'word_set_title': word_set.title, 'form': form})


@login_required
def word_sets_edit(request, pk=None):
    """
    Modify exisiting WordSet or create a new one.
    """
    word_set = get_object_or_404(WordSet, pk=pk, user=request.user) if pk else None
    edit_mode = True if word_set else False
    form = WordSetForm(request.POST or None, request.FILES or None,
                       instance=word_set, user=request.user)
    if form.is_valid():
        form.save()
        if edit_mode:
            return redirect(word_sets_detail, pk=pk)
    if request.method == 'POST':
        return redirect(word_sets_list)
    return render(request, 'word_sets_edit.html', {'form': form, 'edit_mode': edit_mode})

lingo/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Lingo Tool</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
        <script src="{{ STATIC_URL }}bootstrap/js/bootstrap.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.4.5/bootstrap-editable/js/bootstrap-editable.min.js"></script>
        {% block css %}
        <link href="{{ STATIC_URL }}bootstrap/css/bootstrap.css" rel="stylesheet">
        <link href="{{ STATIC_URL }}bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
        <link href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.4.5/bootstrap-editable/css/bootstrap-editable.css" rel="stylesheet">
        <link href="{{ STATIC_URL }}css/base.css" rel="stylesheet">
        {% endblock %}
        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="../assets/js/html5shiv.js"></script>
        <![endif]-->
    </head>

    <body>

    {% block navbar %}
    <div class="navbar-wrapper">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </button>
                <a class="brand" href="{% url main %}">Lingo</a>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        {% if user.is_authenticated %}
                        <li><a href="{% url word_sets_list %}">Moje zestawy</a></li>
                        <li><a href="{% url word_sets_edit %}">Nowy zestaw</a></li>
                        {% endif %}
                    </ul>
                    <ul class="nav pull-right">
                        {% if user.is_authenticated %}
                        <li><a href="#">{{ user.username }}</a></li>
                        <li class="divider-vertical"/>
                        <li><a href="{% url auth_logout %}">Wyloguj się</a></li>
                        {% else %}
                        <li><a href="{% url auth_login %}">Logowanie</a></li>
                        <li><a href="{% url registration_register %}">Rejestracja</a></li>
                        {% endif %}
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>
    </div>
    </div>
    {% endblock %}
    <div id="content" class="container lingo span9 offset2">
    {% block content %}
    {% endblock %}
    </div>
    </body>
</html>

lingo/templates/main.html
{% extends 'base.html' %}

{% block content %}
<div class="hero-unit"> 
    <h1>Lingo</h1>
    <br>
    <p>Lingo to drobne narzędzie wspomagające proces nauki języka angielskiego.</p>
    <p>Jeśli znajdziesz gdzieś interesujący tekst, który niestety zawiera zbyt wiele
    niezrozumiałych terminów, to właśnie Lingo będzie ci w stanie pomóc. Zamiast
    tłumaczyć całość, co często daje dziwaczne efekty, Lingo spróbuje dostosować
    się do Twojego poziomu znajomości języka i zaproponuje - niezależnie od tego, czy będzie
    to recenzja albumu ulubionego zespołu czy specjalistyczny artykuł z dziedziny
    biologii molekularnej - listę słówek i fraz, których najprawdopodobniej
    jeszcze nie znasz. Kiedy je już opanujesz, przeczytanie tekstu ze zrozumieniem
    powinno okazać się znacznie łatwiejsze i przyjemniejsze - nie będziesz już
    sięgać co chwila do słownika.</p>
</div>
{% endblock %}

lingo/templates/word_sets_detail.html
{% extends 'base.html' %}

{% block css %}
    {{ block.super }}
    <link href="{{ STATIC_URL }}css/word_sets_detail.css" rel="stylesheet">
{% endblock %}

{% block content %}
<div id="current_page" style="display: none">{{ request.META.HTTP_HOST }}{{ request.get_full_path }}</div>

<form id="word_sets_detail_form" action="" method="post">{% csrf_token %}
    <div id="toolbar">
        <legend>
            <a href="#" id="title" class="editable" data-type="text" data-pk="{{ word_set_pk }}" data-url="{% url word_sets_detail pk=word_set_pk %}" data-title="Zmień nazwę">{{ word_set_title }}</a>
        </legend>
        <input id="submit_action" name="submit_action" type="hidden">
        <div class="btn-group">
            <button id="mark" class="btn btn-small dropdown-toggle" data-toggle="dropdown" title="Zaznacz"> 
            <i class="icon-large icon-ok"></i> <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <li id="mark_all" class="mark" data-target="tr"><a href="#">wszystkie</a></li>
                <li id="mark_easy" class="mark" data-target="tr.easy"><a href="#">łatwe</a></li>
                <li id="mark_medium" class="mark" data-target="tr.medium"><a href="#">średnie</a></li>
                <li id="mark_hard" class="mark" data-target="tr.hard"><a href="#">trudne</a></li>
            </ul>
        </div>
        <div class="btn-group">
            <button id="auto-next" class="btn btn-small active" title="Automatycznie przechodź do następnego słowa." type="button">
                <i class="icon-large icon-repeat"></i>
            </button>
            <a class="btn btn-small" title="Dodaj więcej słówek" href="{% url word_sets_edit word_set_pk %}">
                <i class="icon-large icon-plus"></i>
            </a>
            <button id="modify" class="btn btn-small dropdown-toggle" data-toggle="dropdown" title="Modyfikuj"> 
                <i class="icon-large icon-wrench"></i> <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <li id="download_?"><a href="#">txt</a></li>
                <li id="download_?"><a href="#">e-mail</a></li>
            </ul>
            <button id="delete" class="btn btn-small" title="Usuń">
                <i class="icon-large icon-trash"></i>
            </button>
        </div>
        <div class="btn-group">
            <button class="btn btn-small dropdown-toggle" data-toggle="dropdown" title="Eksportuj"> 
            <i class="icon-large icon-download-alt"></i> <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <li id="download_txt"><a href="#">txt</a></li>
                <li id="download_email"><a href="#">e-mail</a></li>
            </ul>
        </div>
        <table class="table table-hover" id="table-header">
            <thead>
                <th width="40%">Słowo/fraza</th>
                <th>Tłumaczenie</th>
            </thead>
        </table>
    </div>

   <div id="table-body">
        <table class="table table-hover">
            <tbody>
                {% for word in form.fields.word.queryset %}
                {% if word.difficulty == 0 %}
                <tr class="easy">
                {% elif word.difficulty == 1 %}
                <tr class="medium">
                {% else %}
                <tr class="hard">
                {% endif %}
                    <td width="40%">
                        <label class="checkbox">
                            <input class="in" type="checkbox" name="word" value="{{ word.id }}">
                            <a id="word" class="editable" data-type="text" data-pk="{{ word.id }}" data-url="{% url word_sets_detail pk=word_set_pk %}" data-title="Zmień słowo">{{ word.word }}</a>
                            </input>
                        </label>
                    </td>
                    {% if word.definition %}
                    <td width="60%"><a href="#" class="definition">{{ word.definition }}</a></td>
                    {% else %}
                    <td width="60%"><a href="#" class="definition" data-pk="{{ word.id }}">brak</a></td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</form>

<div id="definition_modal" class="modal hide fade" tabindex="-1">
    <div class="modal-header">
        <h4>Zmień tłumaczenie</h4>
    </div>
    <div class="modal-body"></div>
    <div class="modal-footer">
        <div class="row-fluid">
        <form class="form-inline">
            <input type="text" class="input-xlarge"></input>
            <button type="button" class="btn" data-dismiss="modal" aria-hidden="true">
                <i class="icon-large icon-ok"></i>
            </button>
            <button type="button" class="btn" data-dismiss="modal" aria-hidden="true">
                <i class="icon-large icon-remove"></i>
            </button>
        </form>
        </div>
    </div>
</div>

<script src="{{ STATIC_URL }}js/word_sets_detail.js"></script>
{% endblock %}

lingo/templates/word_sets_edit.html
{% extends 'base.html' %}

{% block content %}
<p>Aby przetworzyć nowy dokument, wybierz plik do załadowania albo wklej jego
zawartość w pole tekstowe.<hr></p>

<form class="form-horizontal" method="post" action="" enctype="multipart/form-data">{% csrf_token %} 
    {% if form.errors %}
    <div class="alert alert-block alert-error">
        {% for field, error in form.errors.items %}
        {{ error }}
        {% endfor %}
    </div>
    {% endif %}

    <!-- Set title field --!>
    {% if not edit_mode %}
    {% if form.title.errors %}
    <div class="control-group error">
    {% else %}
    <div class="control-group">
    {% endif %}
        <label class="control-label" for="input">Nazwa zestawu</label>
        <div class="controls">
            {{ form.title }}
            {% if form.title.errors %}
            <span class="help-inline">
                {{ form.title.errors|join:", " }}
            </span>
            {% endif %}
        </div>
    </div>
    {% endif %}

    <!-- File field --!>
    {% if form.file.errors %}
    <div class="control-group error">
    {% else %}
    <div class="control-group">
    {% endif %}
        <label class="control-label" for="input">Plik</label>
        <div class="controls">
            {{ form.file }}
            {% if form.file.errors %}
            <span class="help-inline">
                {{ form.file.errors|join:", " }}
            </span>
            {% endif %}
        </div>
    </div>

    <!-- Text field --!>
    {% if form.text.errors %}
    <div class="control-group error">
    {% else %}
    <div class="control-group">
    {% endif %}
        <label class="control-label" for="input">Tekst</label>
        <div class="controls">
            <textarea class="field span6" rows="10" id="id_text" name="text" style:"resize:none"/></textarea>
            {% if form.text.errors %}
            <span class="help-inline">
                {{ form.text.errors|join:", " }}
            </span>
            {% endif %}
        </div>
    </div>
    
    <!-- Send button --!>
    <div class="form-actions">
        <input class="btn btn-inverse" type="submit" value="Wyślij"/>
    </div>
</form>
<script src="{{ STATIC_URL }}js/word_sets_edit.js"></script>
{% endblock %}

lingo/templates/word_sets_list.html
{% extends 'base.html' %}

{% block css %}
    {{ block.super }}
    <link href="{{ STATIC_URL }}css/word_sets_list.css" rel="stylesheet">
{% endblock %}

{% block content %}
{% if form.fields.word_set.queryset %}

<form id="word_sets_list_form" action="" method="post">{% csrf_token %} 
    <div id="toolbar">
        <input id="submit_action" name="submit_action" type="hidden">

        <!-- Toolbar -->
        <div class="btn-group">
            <button id="mark_all" class="btn btn-small" title="Zaznacz wszystkie" type="button">
                <i class="icon-large icon-ok"></i>
            </button>
        </div>
        <div class="btn-group">
            <a class="btn btn-small" title="Dodaj nowy zestaw" href="{% url word_sets_edit %}">
                <i class="icon-large icon-plus"></i>
            </a>
            <ul class="dropdown-menu">
                <li id="download_txt"><a href="#">txt</a></li>
                <li id="download_email"><a href="#">e-mail</a></li>
            </ul>
            <button id="delete" class="btn btn-small" title="Usuń">
                <i class="icon-large icon-trash"></i>
            </button>
            <button id="merge" class="btn btn-small" title="Połącz zestawy">
                <i class="icon-large icon-resize-small"></i>
            </button>
        </div>
        <div class="btn-group">
            <button id="download" class="btn btn-small dropdown-toggle" data-toggle="dropdown" title="Eksportuj"> 
                <i class="icon-large icon-download-alt"></i>
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <li id="download_txt"><a href="#">txt</a></li>
                <li id="download_email"><a href="#">e-mail</a></li>
            </ul>
        </div>

        <!-- List of sets -->
        <table class="table table-hover" id="table-header">
            <thead>
                <th width="70%">Nazwa</th>
                <th width="10%">Słówka</th>
                <th>Data utworzenia</th>
            </thead>
        </table>
    </div>

    <div id="table-body">
        <table class="table table-hover">
            <tbody>
            {% for word_set in form.fields.word_set.queryset %}
            <tr id="{{ word_set.id }}">
                <td width="70%">
                    <label class="checkbox">
                    <input class="in" type="checkbox" name="word_set" value="{{ word_set.id }}">
                        <a href="{% url word_sets_detail word_set.id %}">{{ word_set.title }}</a>
                    </input>
                    </label>
                </td>
                <td width="10%">{{ word_set.words_number }}</td>
                <td width="20%">{{ word_set.pub_date|date:"Y-m-d, H:i" }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</form>
<script src="{{ STATIC_URL }}js/word_sets_list.js"></script>

{% else %}

<p>Nie utworzyłeś jeszcze żadnych zestawów słówek. Jeśli chcesz, 
<a href="{% url word_sets_edit %}">stwórz</a> teraz nowy.</p> 

{% endif %}
{% endblock %}